### ISSUE TITLE
Adding an email to the contact form

### ISSUE THREAD

**Issue by evanniedojadlo** [stackbithq/stackbit-theme-fjord#12]
This is likely something that I am completely overlooking but we are attempting to add an email to the contact form so when users submit the message, it goes to my personal email. Where in the stack should this be accomplished?

Stackbit setup: 
Fjord theme
Hugo
Contentful

**Comment by TomasBankauskas** [comment]
Hi @evanniedojadlo, Fjord theme has Netlify forms enabled. That means your contact form is already working. If you want to get the notification to your preferred email, you need to configure Netlify forms.

To configure the form, go to Netlify account, your project page, and check the Form tab. Then go to **“Settings and usage”** and configure Form notifications settings. In **“Settings and usage”** you can find Email notification settings and specify your preferred email there.
