### ISSUE TITLE
Adding a favicon

### ISSUE THREAD

**Issue by evanniedojadlo** [stackbithq/stackbit-theme-fjord#13]
Sorry if I missed reading this somewhere but what is the suggested approach to adding a favicon using this template? 

Thank you,

**Comment by evanniedojadlo** [comment]
The current documentation is specific to Gatsby https://www.stackbit.com/docs/using-gatsby/favicon/ but I'm going to read into hugo and see what I can apply there to make this work.

**Comment by TomasBankauskas** [comment]
Hi @evanniedojadlo If you are using the latest version of the Fjord theme, you can find the favicon option here -> https://www.loom.com/share/005c934f5fb04763afcf7f8b45ad5794

**Comment by evanniedojadlo** [comment]
Thanks. Oh yeah, that looks quite different. This is what I see: [](https://ephemeral-bucket0.s3-us-west-2.amazonaws.com/Screen+Shot+2021-01-25+at+9.07.43+PM.png)

Additional context is that my stack is Fjord, Hugo, Contentful, Github, and Netlify. I had originally deployed this 7 months ago per the github commits.

**Comment by evanniedojadlo** [comment]
I'm closing this out, the quick solution here is just to update my existing template to the latest. I'll look into this now.
