### ISSUE TITLE
Remove JS From Fjord Theme

### ISSUE THREAD

**Issue by BayuAngora** [stackbithq/stackbit-theme-fjord#3]
Dear All 

I want to remove JavaScript (main.js and plugin.js) from my website. But everytime I remove those JavaScript files, my sidebar is dissapear. How to fix this issue? 

Regards

**Comment by TomasBankauskas** [comment]
Hey @BayuAngora, 

if you want to remove JavaScript from your website, you have to make some CSS adjustments. For the sidebar, remove or comment out the _animations.scss stylesheet from the `assets/sass/main.scss` file, i.e.:

```
@import "imports/animations";
```

You should also make the adjustments for the site navigation to work on small screens as it depends on JavaScript.

**Comment by BayuAngora** [comment]
Thanks, Tom. I want to remove JS completely. Because I don't need scroll up feature. And for mobile menu, I will change it to standard menu without hamburger and JS to open it.

**Comment by BayuAngora** [comment]
Thanks, Tom. I want to remove JS completely. Because I don't need scroll up feature. And for mobile menu, I will change it to standard menu without hamburger and JS to open it.
By the way, how to paginate blog without JavaScript? Because the default setting is 10 posts per page, but I want to change it to 6 posts per page.
I use **paginate: 6** on config.yaml but the posts appear still not change?

**Comment by BayuAngora** [comment]
It works. Thanks.
