### ISSUE TITLE
Issue About Limit Paginator Post Per Page

### ISSUE THREAD

**Issue by BayuAngora** [stackbithq/stackbit-theme-fjord#4]
Dear All

I need to limit my blog post from default 10 posts per page to 6 posts per page for this website ->
https://angora.netlify.com/blog/

This is my code on main.html file ->
https://raw.githubusercontent.com/BayuAngora/angora/master/layouts/_default/main.html

Even that current code above is strange, because it display more than 10 posts per page. How to fix this issue?

**Comment by smnh** [comment]
@BayuAngora, currently Stackbit themes written on Unibit does not support pagination.
What I can suggest is that you add pagination to your site manually using Hugo's build in pagination mechanism: https://gohugo.io/templates/pagination/

**Comment by BayuAngora** [comment]
Thanks, Smith. I tried the tips above and it really helps.

**Comment by BayuAngora** [comment]
Thanks, Simon. The paginator part is fixed. But the prev next code above is not working. 
Even when I change to this code:

`
      <nav class="pagination">
        <div class="nav-links">
          <a class="older-posts button" href="{{ $paginator.Prev.URL }}"><span class="icon-arrow-left" aria-hidden="true"></span></a>
          <a class="newer-posts button" href="{{ $paginator.Next.URL }}"><span class="icon-arrow-right" aria-hidden="true"></span></a>
        </div>
      </nav>
`

I still getting error.

**Comment by smnh** [comment]
I found two issues:

1. The `footer.html` tries to do this `{{ .Site.Params.footer.content | safeHTML }}`. But there is no `content` property in `params.footer` in `config.yaml` file.
2. I suggest using `{{if .Next}}{{.Next.Permalink}}{{end}}` instead of `.PrevPage`

Then it works

**Comment by BayuAngora** [comment]
> I found two issues:
> 
> 1. The `footer.html` tries to do this `{{ .Site.Params.footer.content | safeHTML }}`. But there is no `content` property in `params.footer` in `config.yaml` file.
> 2. I suggest using `{{if .Next}}{{.Next.Permalink}}{{end}}` instead of `.PrevPage`
> 
> Then it works.
> 
> P.S.:
> Hugo has good documentation and large community, I suggest directing these sort of questions there. Although this repo is a [Unibit](https://docs.stackbit.com/unibit/) theme that can be converted to Hugo site with Stackbit. Any custom changes made to Hugo site after Stackbit have created it, is out of scope of Unibit and this repo :)

Thanks for support. I will try it.
